### ISSUE TITLE
Error after using it for a while

### ISSUE THREAD

**Issue by ExTaCy1337** [pyroch/TwitchGrobs#1]
Starts and runs fine , but after some time I get this, I can't let it work overnight, it probably works for 5-10 minutes.

Unhandled exception. OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:61301/session/a1b016b4bcf57bad8787b0f526dca13f/url timed out after 60 seconds.
 ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
   at TwitchGrobs.Program.BrowseLogic()
   at TwitchGrobs.Program.Main()
[1613608555.007][SEVERE]: Timed out receiving message from renderer: 299.418
[1613608555.008][SEVERE]: Timed out receiving message from renderer: 299.418

**Comment by pyroch** [comment]
Try 0.5.6, can't be sure if its fixed. Also make sure the chrome is running on version 88.0.4324.182 (latest)
